sudo: false
language: rust

cache: cargo

rust:
    - nightly
    - beta
    - stable
os:
    - linux
    - osx
matrix:
 allow_failures:
   - rust: nightly
before_script: (cargo install rustfmt || true)
script:
  - |
    export PATH=$PATH:~/.cargo/bin &&
    cargo fmt -- --write-mode=diff &&
    cargo build
